name: oseepod

services:
  postgres:
    image: postgres
    container_name: oseepod-postgres
    environment:
      POSTGRES_DB: oseepod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - oseepod_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  oseepod_postgres_data: